language: python
sudo: required

python:
  - 3.6

services:
  - docker

install:
  - sudo apt-get install -y nmap
  - pip install -r requirements.txt
  - sudo echo { | sudo tee -a /etc/docker/daemon.json
  - sudo echo "    \"userland-proxy\": false" | sudo tee -a /etc/docker/daemon.json
  - sudo echo } | sudo tee -a /etc/docker/daemon.json
  - sudo service docker restart

script:
  - python ci_automated_tests.py
