language: python
sudo: required

python:
  - 3.6

services:
  - docker

install:
  - sudo apt-get install -y nmap
  - pip install -r requirements.txt
  - sudo apt-get install pastebinit
  #- sudo cp .travis_docker_config /etc/docker/daemon.json
  #- sudo service docker restart

script:
  - python nmap_scan_all.py && pastebinit -P -b pastebin.com _batch_scan_* nmap_scan_all.out nmap_scan_all.err

